"""
system/startup.py — Persistent Runtime & Auto-Start for Jarvis.

Handles (in priority order):
  1. Windows Startup folder (VBScript launcher — most reliable, no admin needed)
  2. Windows Task Scheduler as fallback
  3. Windows Registry as last resort

Concept: Jarvis should launch silently after Windows login.
A VBScript file is placed in the user's Startup folder. Windows
automatically runs everything in this folder at logon. VBScript
is chosen over .bat because it launches pythonw.exe with zero
console window flash — completely invisible to the user.
"""

import logging
import os
import shutil
import sys
import subprocess
import winreg

log = logging.getLogger(__name__)

TASK_NAME = "JarvisAssistant"
APP_NAME = "Jarvis"
VBS_FILENAME = "jarvis_launcher.vbs"


def get_python_path() -> str:
    """Get path to python.exe in the venv."""
    # Prefer the project venv's python.exe
    project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    venv_python = os.path.join(project_dir, ".venv", "Scripts", "python.exe")
    if os.path.exists(venv_python):
        return venv_python

    # Fallback: python.exe next to current interpreter
    python_dir = os.path.dirname(sys.executable)
    python_exe = os.path.join(python_dir, "python.exe")
    if os.path.exists(python_exe):
        return python_exe
    return sys.executable  # last resort


def get_main_script() -> str:
    """Get absolute path to main.py."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "main.py"))


def get_project_dir() -> str:
    """Get absolute path to the project root directory."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def get_startup_folder() -> str:
    """Get the Windows Startup folder path."""
    return os.path.join(
        os.environ.get("APPDATA", ""),
        "Microsoft", "Windows", "Start Menu", "Programs", "Startup"
    )


def _generate_vbs_content() -> str:
    """Generate the VBScript launcher content."""
    project_dir = get_project_dir()
    pythonw = get_python_path()
    main_script = get_main_script()

    lines = [
        "' ============================================================",
        "' jarvis_launcher.vbs - Silent Startup Launcher for J.A.R.V.I.S",
        "'",
        "' Auto-generated by system/startup.py",
        "' Launches Jarvis using pythonw.exe (no console window)",
        "' ============================================================",
        "",
        "Dim projectDir, pythonw, mainScript, shell",
        "",
        'projectDir  = "' + project_dir + '"',
        'pythonw     = "' + pythonw + '"',
        'mainScript  = "' + main_script + '"',
        "",
        'Set shell = CreateObject("WScript.Shell")',
        "",
        "' Set working directory to project root",
        "shell.CurrentDirectory = projectDir",
        "",
        "' Launch Jarvis silently (0 = hidden, False = don't wait)",
        'shell.Run """" & pythonw & """ """ & mainScript & """", 0, False',
        "",
        "Set shell = Nothing",
    ]
    return "\r\n".join(lines) + "\r\n"


# ── Primary Method: Startup Folder ────────────────────────────

def install_startup_folder() -> bool:
    """
    Place a VBScript launcher in the Windows Startup folder.

    This is the most reliable, user-friendly method:
      - No admin privileges required
      - User can see/manage it in shell:startup
      - VBScript ensures zero console window flash
      - Sets correct working directory for the project
    """
    startup_folder = get_startup_folder()
    if not os.path.isdir(startup_folder):
        log.error("Startup folder not found: %s", startup_folder)
        return False

    vbs_content = _generate_vbs_content()
    vbs_path = os.path.join(startup_folder, VBS_FILENAME)

    # Also save a copy in the project scripts/ folder
    scripts_dir = os.path.join(get_project_dir(), "scripts")
    os.makedirs(scripts_dir, exist_ok=True)
    scripts_copy = os.path.join(scripts_dir, VBS_FILENAME)

    try:
        with open(vbs_path, "w", encoding="utf-8") as f:
            f.write(vbs_content)
        log.info("VBS launcher installed to Startup folder: %s", vbs_path)

        # Keep a copy in the project
        with open(scripts_copy, "w", encoding="utf-8") as f:
            f.write(vbs_content)

        return True
    except Exception as e:
        log.error("Startup folder install failed: %s", e)
        return False


# ── Fallback: Task Scheduler ─────────────────────────────────

def install_task_scheduler() -> bool:
    """
    Create a Windows Task Scheduler task to launch Jarvis at logon.

    Uses LIMITED privilege level (no admin needed).
    Falls back to registry if this fails.
    """
    python = get_python_path()
    script = get_main_script()

    cmd = [
        "schtasks", "/create",
        "/tn", TASK_NAME,
        "/tr", f'"{python}" "{script}"',
        "/sc", "ONLOGON",
        "/rl", "LIMITED",   # No admin required
        "/f",               # Force overwrite if exists
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            log.info("Task Scheduler entry created: %s", TASK_NAME)
            return True
        else:
            log.error("schtasks failed: %s", result.stderr)
            return install_registry_startup()
    except Exception as e:
        log.error("Task Scheduler setup failed: %s", e)
        return install_registry_startup()


# ── Last Resort: Registry ─────────────────────────────────────

def install_registry_startup() -> bool:
    """
    Add Jarvis to Windows startup via registry.

    Writes to HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run
    which doesn't require admin privileges.
    """
    python = get_python_path()
    script = get_main_script()
    value = f'"{python}" "{script}"'

    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Run",
            0, winreg.KEY_SET_VALUE,
        )
        winreg.SetValueEx(key, APP_NAME, 0, winreg.REG_SZ, value)
        winreg.CloseKey(key)
        log.info("Registry startup entry created: %s", APP_NAME)
        return True
    except Exception as e:
        log.error("Registry startup failed: %s", e)
        return False


# ── Master Install (tries all methods) ────────────────────────

def install_auto_start() -> bool:
    """
    Install Jarvis auto-start using the best available method.

    Priority: Startup Folder > Task Scheduler > Registry
    """
    # Method 1: Startup folder (preferred)
    if install_startup_folder():
        log.info("Auto-start installed via Startup folder (primary)")
        return True

    # Method 2: Task Scheduler
    log.warning("Startup folder failed, trying Task Scheduler...")
    if install_task_scheduler():
        log.info("Auto-start installed via Task Scheduler (fallback)")
        return True

    # Method 3: Registry (last resort)
    log.warning("Task Scheduler failed, trying Registry...")
    if install_registry_startup():
        log.info("Auto-start installed via Registry (last resort)")
        return True

    log.error("All auto-start methods failed!")
    return False


# ── Uninstall (removes all methods) ──────────────────────────

def uninstall_startup() -> bool:
    """Remove all auto-start entries (Startup folder, Task Scheduler, Registry)."""
    success = True

    # Remove from Startup folder
    vbs_path = os.path.join(get_startup_folder(), VBS_FILENAME)
    try:
        if os.path.exists(vbs_path):
            os.remove(vbs_path)
            log.info("Startup folder launcher removed")
    except Exception as e:
        log.warning("Could not remove Startup folder entry: %s", e)
        success = False

    # Remove Task Scheduler entry
    try:
        result = subprocess.run(
            ["schtasks", "/delete", "/tn", TASK_NAME, "/f"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            log.info("Task Scheduler entry removed")
        else:
            log.warning("Task Scheduler removal: %s", result.stderr.strip())
    except Exception as e:
        log.warning("Could not remove Task Scheduler entry: %s", e)
        success = False

    # Remove registry entry
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Run",
            0, winreg.KEY_SET_VALUE,
        )
        winreg.DeleteValue(key, APP_NAME)
        winreg.CloseKey(key)
        log.info("Registry startup entry removed")
    except FileNotFoundError:
        pass  # Already removed
    except Exception as e:
        log.warning("Could not remove registry entry: %s", e)
        success = False

    return success


# ── Status Check ─────────────────────────────────────────────

def is_installed() -> bool:
    """Check if auto-start is configured via any method."""
    # Check Startup folder
    vbs_path = os.path.join(get_startup_folder(), VBS_FILENAME)
    if os.path.exists(vbs_path):
        return True

    # Check Task Scheduler
    try:
        result = subprocess.run(
            ["schtasks", "/query", "/tn", TASK_NAME],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            return True
    except Exception:
        pass

    # Check registry
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Run",
            0, winreg.KEY_READ,
        )
        winreg.QueryValueEx(key, APP_NAME)
        winreg.CloseKey(key)
        return True
    except (FileNotFoundError, OSError):
        return False


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    if "--install" in sys.argv:
        if install_auto_start():
            print(f"OK: {APP_NAME} will start automatically at login")
        else:
            print(f"FAIL: Could not set up auto-start")
    elif "--uninstall" in sys.argv:
        if uninstall_startup():
            print(f"OK: {APP_NAME} auto-start removed")
        else:
            print(f"FAIL: Could not remove auto-start")
    elif "--status" in sys.argv:
        status = "installed" if is_installed() else "not installed"
        print(f"Auto-start: {status}")
    else:
        print("Usage: python startup.py [--install | --uninstall | --status]")
