' ============================================================
' jarvis_launcher.vbs - Silent Startup Launcher for J.A.R.V.I.S
'
' Auto-generated by system/startup.py
' Launches Jarvis using pythonw.exe (no console window)
' ============================================================

Dim projectDir, pythonw, mainScript, shell

projectDir  = "c:\Users\Siddharth Reddy\projects\jarvis"
pythonw     = "c:\Users\Siddharth Reddy\projects\jarvis\.venv\Scripts\python.exe"
mainScript  = "c:\Users\Siddharth Reddy\projects\jarvis\main.py"

Set shell = CreateObject("WScript.Shell")

' Set working directory to project root
shell.CurrentDirectory = projectDir

' Launch Jarvis silently (0 = hidden, False = don't wait)
shell.Run """" & pythonw & """ """ & mainScript & """", 0, False

Set shell = Nothing
